id: P000228
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །རྫོགས་ཆེན་ཨ་ཏི་ཟབ་དོན་སྙིང་པོའི་ཐོག་མར་དགེ་བ་ལམ་སྟེགས་སྔོན་འགྲོའི་ཆོས་སྤྱོད་ཟུར་དུ་ཕྱུང་པ་བཞུགས་སོ།།
  authors:
  - མཛད་པ་པོ། སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེའམ་གཏེར་བདག་གླིང་པ། མི་འགྱུར་དཔལ་སྒྲོན།
  layers:
  - book_title
  - author
  - yigchung
  id: SHE-RTD-022
web_metadata:
  title:
    en: A Selection of the Prayer Texts for the Preliminary Practices of the Profound
      Unsurpassable Meaning of the Great Perfection – Ati Zabdon
    bo: རྫོགས་ཆེན་ཨ་ཏི་ཟབ་དོན་སྙིང་པོའི་ཐོག་མར་དགེ་བ་ལམ་སྟེགས་སྔོན་འགྲོའི་ཆོས་སྤྱོད་ཟུར་དུ་ཕྱུང་པ་བཞུགས་སོ།
  collection:
    en: Treasury of Precious Termas–  Book 22
    bo: རིན་ཆེན་གཏེར་མཛོད།–  དེབ། ༢༢
  author:
    en: Authors:Jetsun Mingyur Paldron,Minling Terchen Gyurme Dorje
    bo: རྗེ་བཙུན་མི་འགྱུར་དཔལ་སྒྲོན།,སྨིན་གླིང་གཏེར་ཆེན་འགྱུར་མེད་རྡོ་རྗེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-RTD-022
  category:
    en: Preliminary Practices
    bo: སྔོན་འགྲོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-022.epub
  description:
    en: ''
    bo: ''
